const testData = {
    "styleColor": "blue",
    "styleColumn": 4,
    "data": [
      {
        "field": "",
        "title": "测试标题01",
        "value": "测试数据01",
        "unit": "",
        "type": "text",
        "cellRange": 1,
        "link": false,
        "linkpath": "",
        "cutoff": false,
        "scope": ""
      },{
        "field": "",
        "title": "测试标题01",
        "value": "测试数据01",
        "unit": "",
        "type": "text",
        "cellRange": 1,
        "link": false,
        "linkpath": "",
        "cutoff": false,
        "scope": ""
      },
      {
        "field": "",
        "title": "测试标题01",
        "value": "测试数据01",
        "unit": "",
        "type": "text",
        "cellRange": 1,
        "link": false,
        "linkpath": "",
        "cutoff": false,
        "scope": ""
      },
      {
        "field": "",
        "title": "测试标题01",
        "value": "测试数据01",
        "unit": "",
        "type": "text",
        "cellRange": 1,
        "link": false,
        "linkpath": "",
        "cutoff": false,
        "scope": ""
      },
      {
        "field": "",
        "title": "测试标题01",
        "value": "测试数据01",
        "unit": "",
        "type": "text",
        "cellRange": 1,
        "link": false,
        "linkpath": "",
        "cutoff": false,
        "scope": ""
      },
      {
        "field": "",
        "title": "测试标题01",
        "value": "测试数据01",
        "unit": "",
        "type": "text",
        "cellRange": 1,
        "link": false,
        "linkpath": "",
        "cutoff": false,
        "scope": ""
      },
      {
        "field": "",
        "title": "测试标题01",
        "value": "测试数据01",
        "unit": "",
        "type": "text",
        "cellRange": 2,
        "link": false,
        "linkpath": "",
        "cutoff": false,
        "scope": ""
      },
      {
        "field": "",
        "title": "测试标题01",
        "value": "测试数据01",
        "unit": "",
        "type": "text",
        "cellRange": 4,
        "link": false,
        "linkpath": "",
        "cutoff": false,
        "scope": ""
      },
      {
        "field": "",
        "title": "附件",
        "value": [
          {
            "appType": "",
            "creator": "WB272411",
            "downloadUrl": "https://www.baidu.com",
            "encrypt": "n",
            "ext": "png",
            "extName": "png",
            "formUuid": "FORM-IJ866NA1G8TQWYHVY712H0L3SX7I26QUKEXPKW9",
            "gmtCreate": 1630394577214,
            "gmtModified": 1630394577214,
            "gmtUpload": 1630394577214,
            "isDeleted": "n",
            "memo": "",
            "modifier": "WB272411",
            "name": "资源 14@6x.png",
            "needWaterMark": false,
            "open": "n",
            "path": "2783df26-ea69-4935-91bc-978f8f4f299f.png",
            "previewUrl": "https://www.baidu.com",
            "procInstId": "",
            "shardKey": "",
            "size": 109429,
            "source": "",
            "status": "",
            "systemType": "",
            "type": "OSS",
            "url": "https://www.baidu.com"
          },
          {
            "appType": "",
            "creator": "WB272411",
            "downloadUrl": "https://www.baidu.com",
            "encrypt": "n",
            "ext": "png",
            "extName": "png",
            "formUuid": "FORM-IJ866NA1G8TQWYHVY712H0L3SX7I26QUKEXPKW9",
            "gmtCreate": 1630394581096,
            "gmtModified": 1630394581096,
            "gmtUpload": 1630394581096,
            "isDeleted": "n",
            "memo": "",
            "modifier": "WB272411",
            "name": "资源 14@6x.png",
            "needWaterMark": false,
            "open": "n",
            "path": "39fc1038-fc6c-4177-8e50-348075682721.png",
            "previewUrl": "https://www.baidu.com",
            "procInstId": "",
            "shardKey": "",
            "size": 109429,
            "source": "",
            "status": "",
            "systemType": "",
            "type": "OSS",
            "url": "https://www.baidu.com"
          },
          {
            "appType": "",
            "creator": "WB272411",
            "downloadUrl": "https://www.baidu.com",
            "encrypt": "n",
            "ext": "png",
            "extName": "png",
            "formUuid": "FORM-IJ866NA1G8TQWYHVY712H0L3SX7I26QUKEXPKW9",
            "gmtCreate": 1630394588161,
            "gmtModified": 1630394588161,
            "gmtUpload": 1630394588161,
            "isDeleted": "n",
            "memo": "",
            "modifier": "WB272411",
            "name": "资源 14@6x.png",
            "needWaterMark": false,
            "open": "n",
            "path": "63bd0e59-1252-4d21-a7ce-fd375c6ede15.png",
            "previewUrl": "https://www.baidu.com",
            "procInstId": "",
            "shardKey": "",
            "size": 109429,
            "source": "",
            "status": "",
            "systemType": "",
            "type": "OSS",
            "url": "https://www.baidu.com"
          }
        ],
        "unit": "",
        "type": "attachment",
        "cellRange": 4,
        "link": false,
        "linkpath": "",
        "cutoff": false,
        "scope": ""
      }
    ]
}